[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
types = { workspace = true }
bench = { workspace = true }

axum = { version = "0.7.9", features = ["macros"] }
tokio = { workspace = true }
tower-http = { version = "0.6.1", features = ["cors", "fs", "trace"] }
