[package]
name = "bin"
version.workspace = true
edition.workspace = true

[dependencies]
api = { workspace = true }

tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = "0.3.19"
